import "bootstrap";
import "jquery";
// import "../components/datepicker.js";
import "../components/grant_role.js";
// import "../components/member.js";
import "../components/navbar.js";
import "../components/password.js";
import "../components/producttype.js";
// import "../components/search_range.js";
import "../components/subscription.js";
import "../components/subscription_bis.js";
import "../components/upload_image.js";
//import "../components/uploadprodpics.js";
import "../components/global_variable.js";
import "../components/progress_bar.js";
